### PR TITLE
fix: respect of all parents

### LINKED ISSUE #69: Add support for mocking inherited members
It looks like the `MockComponent` method does not setup methods from inherited methods. The code for setting up mock methods for both [MockDirective](https://github.com/ike18t/ng-mocks/blob/master/lib/mock-directive/mock-directive.ts#L73) and [MockComponent](https://github.com/ike18t/ng-mocks/blob/master/lib/mock-component/mock-component.ts#L96) only gets methods from the class's prototype but doesn't traverse up the prototype chain to handle inheritance.

For example, Angular Material's [MatSidenav component](https://github.com/angular/components/blob/master/src/material/sidenav/sidenav.ts#L79) extends the [MatDrawer component](https://github.com/angular/components/blob/master/src/material/sidenav/drawer.ts#L140) and methods defined on MatDrawer are not setup when mocking MatSidenav. This can cause some confusion when some methods on a type are setup and others are not.

[Here's a small stackblitz that reproduces the error](https://stackblitz.com/edit/angular-scjuj2)

### PR DESCRIPTION
**Pull request by satanTime**
Closes #69

### CODE REVIEW

**Comment by satanTime** [comment]
Hi @ike18t, I've updated PR avoiding usage of the MockBuilder part.

**Comment by satanTime** [comment]
Hi @ike18t, one sec, let me solve the conflict.

**Comment by ike18t** [comment]
@satanTime I merged another of your PRs and it caused a merge conflict in this one.

**Comment by satanTime** [comment]
aha, there's an intersection. this one has been fixed. once it has been merged I can update the MockBuilder's PR.

**Pull request merged**
