### PR TITLE
UT for https://github.com/ike18t/ng-mocks/pull/35

### PR DESCRIPTION
**Pull request by satanTime**
Hi @ike18t, please check UT for the issue we discussed in PR 35.

### CODE REVIEW

**Comment by satanTime** [comment]
Hey @ike18t, might you release new version?
Master works good for me. Would be great to have changes in other projects.

**Comment by ike18t** [comment]
Just released your changes.

**Comment by satanTime** [comment]
Thanks!

**Comment by satanTime** [comment]
Looks like it's failed: https://travis-ci.org/ike18t/ng-mocks

**Comment by ike18t** [comment]
🤬

**Comment by satanTime** [comment]
I used `npm audit fix` when added new packages, maybe that caused the issue.

**Comment by ike18t** [comment]
My workspace was on an older version of node which didn't update my package-lock.json.  I just pushed the update.  The release should not be impacted.

**Comment by satanTime** [comment]
Thanks!

**Pull request merged**
